server:
  port: 8186

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 123456
    url: jdbc:mysql:///hypergraph
#    username: root
#    password: 111111
#    url: jdbc:mysql:///software6


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/plot
